(ns ^:figwheel-hooks ponceleo.core
  (:require
    [ponceleo.utils.lorem-ipsum :refer [random-sentence]]
    [reagent.core :as reagent :refer [atom]]
    [reagent.dom :as rdom]
    [reagent.session :as session]
    [reitit.frontend :as reitit]
    [clerk.core :as clerk]
    [accountant.core :as accountant]
    [ponceleo.pages.home.index :refer [home-page]]
    [ponceleo.pages.about.index :refer [about-page]]))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div {:class ["overflow-x-hidden"]}
       [page]])))
        ;[:footer {:class ["my-24 text-small"]}
       ; [:p "ponceleo was generated by the "
       ;  [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]


;; -------------------------
;; Routes

(def router
  (reitit/router
    [["/" :index]
     ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page))


;; -------------------------
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)))

    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))

(defn ^:after-load re-render []
  (mount-root))
